namespace DotPython.Compiler.Bytecode;

public enum PythonOpCode
{
    LoadConstant = 0,
    LoadName = 1,
    StoreName = 2,
    LoadLocal = 3,
    StoreLocal = 4,
    PopTop = 5,
    UnaryPositive = 6,
    UnaryNegative = 7,
    UnaryInvert = 8,
    UnaryNot = 9,
    BinaryAdd = 10,
    BinarySubtract = 11,
    BinaryMultiply = 12,
    BinaryTrueDivide = 13,
    BinaryFloorDivide = 14,
    BinaryModulo = 15,
    BinaryPower = 16,
    CompareEqual = 17,
    CompareNotEqual = 18,
    CompareLessThan = 19,
    CompareLessThanOrEqual = 20,
    CompareGreaterThan = 21,
    CompareGreaterThanOrEqual = 22,
    CopyTop = 23,
    RotateTwo = 24,
    RotateThree = 25,
    Jump = 26,
    JumpIfFalse = 27,
    JumpIfFalseOrPop = 28,
    JumpIfTrueOrPop = 29,
    MakeFunction = 30,
    Call = 31,
    ReturnValue = 32,
    ReturnNone = 33,
    LoadCell = 34,
    StoreCell = 35,
}
