namespace DotPython.Compiler.Bytecode;

public enum PythonOpCode
{
    LoadConstant,
    LoadName,
    StoreName,
    PopTop,
    UnaryPositive,
    UnaryNegative,
    UnaryInvert,
    UnaryNot,
    BinaryAdd,
    BinarySubtract,
    BinaryMultiply,
    BinaryTrueDivide,
    BinaryFloorDivide,
    BinaryModulo,
    BinaryPower,
    CompareEqual,
    CompareNotEqual,
    CompareLessThan,
    CompareLessThanOrEqual,
    CompareGreaterThan,
    CompareGreaterThanOrEqual,
    CopyTop,
    RotateTwo,
    RotateThree,
    Jump,
    JumpIfFalse,
    JumpIfFalseOrPop,
    JumpIfTrueOrPop,
    Call,
    ReturnNone,
}
