<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../DotPython.Language/DotPython.Language.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource
            Include="Unicode/UnicodeNameIndex16.bin"
            LogicalName="DotPython.UnicodeNameIndex16"
        />
    </ItemGroup>
</Project>
