using System.Globalization;
using System.Text;
using DotPython.Contracts;

namespace DotPython.Build.Tasks;

internal static class CSharpModuleFacadeGenerator
{
    internal static string Generate(PythonModuleContract contract, string artifactResourceName)
    {
        ArgumentNullException.ThrowIfNull(contract);
        ArgumentException.ThrowIfNullOrWhiteSpace(artifactResourceName);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(contract.ClrNamespace).AppendLine(";");
        builder.AppendLine();
        AppendInterface(builder, contract);
        builder.AppendLine();
        builder
            .Append("/// <summary>Provides typed access to the '")
            .Append(contract.ModuleName)
            .AppendLine("' DotPython module.</summary>");
        builder
            .Append("public sealed class ")
            .Append(contract.ClrTypeName)
            .Append(" : I")
            .Append(contract.ClrTypeName)
            .AppendLine(", global::System.IAsyncDisposable");
        builder.AppendLine("{");
        builder
            .Append("    private const string ArtifactResourceName = ")
            .Append(Literal(artifactResourceName))
            .AppendLine(";");
        builder.AppendLine(
            "    private static readonly global::System.Lazy<global::DotPython.PythonModuleDefinition> ModuleDefinition = new(CreateDefinition);"
        );
        builder.AppendLine("    private readonly global::DotPython.IDotPythonModule _module;");
        builder.AppendLine();
        AppendRegistration(builder, contract);
        builder.AppendLine();
        builder
            .Append("    private ")
            .Append(contract.ClrTypeName)
            .AppendLine("(global::DotPython.IDotPythonModule module)");
        builder.AppendLine("    {");
        builder.AppendLine("        _module = module;");
        builder.AppendLine("    }");
        builder.AppendLine();
        AppendLoadMethod(builder, contract);
        foreach (var function in contract.Functions)
        {
            builder.AppendLine();
            AppendFunction(builder, function, "_module");
        }

        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask DisposeAsync() =>");
        builder.AppendLine("        _module.DisposeAsync();");
        builder.AppendLine();
        AppendDefinitionFactory(builder, contract);
        builder.AppendLine();
        AppendContractFactory(builder, contract);
        builder.AppendLine();
        AppendProviderClient(builder, contract);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendInterface(StringBuilder builder, PythonModuleContract contract)
    {
        builder
            .Append("/// <summary>Defines typed access to the '")
            .Append(contract.ModuleName)
            .AppendLine("' DotPython module.</summary>");
        builder.Append("public interface I").Append(contract.ClrTypeName).AppendLine();
        builder.AppendLine("{");
        foreach (var function in contract.Functions)
        {
            AppendFunctionSignature(builder, function, "    ");
            builder.AppendLine(";");
        }

        builder.AppendLine("}");
    }

    private static void AppendRegistration(StringBuilder builder, PythonModuleContract contract)
    {
        builder.AppendLine(
            "    /// <summary>Gets the host registration for this module.</summary>"
        );
        builder
            .Append("    public static global::DotPython.PythonModuleRegistration<I")
            .Append(contract.ClrTypeName)
            .AppendLine("> Registration { get; } =");
        builder.AppendLine("        new(");
        builder.Append("            ").Append(Literal(contract.ModuleName)).AppendLine(",");
        builder
            .Append("            global::DotPython.Contracts.PythonModuleStatePolicy.")
            .Append(contract.StatePolicy)
            .AppendLine(",");
        builder.AppendLine("            static provider => new ProviderClient(provider)");
        builder.AppendLine("        );");
    }

    private static void AppendLoadMethod(StringBuilder builder, PythonModuleContract contract)
    {
        builder.AppendLine(
            "    /// <summary>Loads a runtime-owned instance of the compiled module.</summary>"
        );
        builder
            .Append("    public static async global::System.Threading.Tasks.ValueTask<")
            .Append(contract.ClrTypeName)
            .AppendLine("> LoadAsync(");
        builder.AppendLine("        global::DotPython.IDotPythonModuleRuntime runtime,");
        builder.AppendLine(
            "        global::System.Threading.CancellationToken cancellationToken = default"
        );
        builder.AppendLine("    )");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(runtime);");
        builder.AppendLine("        var module = await runtime.LoadModuleAsync(");
        builder.AppendLine("            ModuleDefinition.Value,");
        builder.AppendLine("            cancellationToken");
        builder.AppendLine("        ).ConfigureAwait(false);");
        builder.Append("        return new ").Append(contract.ClrTypeName).AppendLine("(module);");
        builder.AppendLine("    }");
    }

    private static void AppendFunction(
        StringBuilder builder,
        PythonFunctionContract function,
        string invocationTarget
    )
    {
        builder
            .Append("    /// <summary>Invokes the '")
            .Append(function.PythonName)
            .AppendLine("' Python export.</summary>");
        AppendFunctionSignature(builder, function, "    public ");
        builder.AppendLine(" =>");
        builder.Append("        ").Append(invocationTarget).Append(".InvokeAsync");
        if (!IsVoid(function.ReturnType))
        {
            builder.Append('<').Append(TypeName(function.ReturnType)).Append('>');
        }

        builder.AppendLine("(");
        builder
            .Append("            new global::DotPython.PythonFunctionInvocation(")
            .Append(Literal(function.PythonName));
        if (function.Parameters.Count != 0)
        {
            builder.AppendLine(",");
            builder.Append("                [");
            for (var index = 0; index < function.Parameters.Count; index++)
            {
                if (index != 0)
                {
                    builder.Append(", ");
                }

                builder.Append(function.Parameters[index].ClrName);
            }

            builder.Append(']');
        }

        builder.AppendLine("),");
        builder.AppendLine("            cancellationToken");
        builder.AppendLine("        );");
    }

    private static void AppendFunctionSignature(
        StringBuilder builder,
        PythonFunctionContract function,
        string prefix
    )
    {
        var indent = new string(' ', prefix.TakeWhile(character => character == ' ').Count());
        var parameterIndent = indent + "    ";
        builder.Append(prefix).Append("global::System.Threading.Tasks.ValueTask");
        if (!IsVoid(function.ReturnType))
        {
            builder.Append('<').Append(TypeName(function.ReturnType)).Append('>');
        }

        builder.Append(' ').Append(function.ClrName).AppendLine("(");
        for (var index = 0; index < function.Parameters.Count; index++)
        {
            var parameter = function.Parameters[index];
            builder
                .Append(parameterIndent)
                .Append(TypeName(parameter.Type))
                .Append(' ')
                .Append(parameter.ClrName)
                .AppendLine(",");
        }

        builder
            .Append(parameterIndent)
            .AppendLine("global::System.Threading.CancellationToken cancellationToken = default");
        builder.Append(indent).Append(')');
    }

    private static void AppendDefinitionFactory(
        StringBuilder builder,
        PythonModuleContract contract
    )
    {
        builder.AppendLine(
            "    private static global::DotPython.PythonModuleDefinition CreateDefinition()"
        );
        builder.AppendLine("    {");
        builder
            .Append("        using var resource = typeof(")
            .Append(contract.ClrTypeName)
            .AppendLine(").Assembly.GetManifestResourceStream(ArtifactResourceName)");
        builder.AppendLine(
            "            ?? throw new global::System.InvalidOperationException(\"The embedded DotPython module artifact is missing.\");"
        );
        builder.AppendLine("        using var artifact = new global::System.IO.MemoryStream();");
        builder.AppendLine("        resource.CopyTo(artifact);");
        builder.AppendLine(
            "        return new global::DotPython.PythonModuleDefinition(CreateContract(), artifact.ToArray());"
        );
        builder.AppendLine("    }");
    }

    private static void AppendProviderClient(StringBuilder builder, PythonModuleContract contract)
    {
        builder
            .Append("    private sealed class ProviderClient : I")
            .Append(contract.ClrTypeName)
            .AppendLine();
        builder.AppendLine("    {");
        builder.AppendLine(
            "        private readonly global::DotPython.IDotPythonModuleProvider _provider;"
        );
        builder.AppendLine();
        builder.AppendLine(
            "        internal ProviderClient(global::DotPython.IDotPythonModuleProvider provider)"
        );
        builder.AppendLine("        {");
        builder.AppendLine("            _provider = provider;");
        builder.AppendLine("        }");
        foreach (var function in contract.Functions)
        {
            builder.AppendLine();
            AppendProviderFunction(builder, function);
        }

        builder.AppendLine("    }");
    }

    private static void AppendProviderFunction(
        StringBuilder builder,
        PythonFunctionContract function
    )
    {
        builder.AppendLine("        /// <inheritdoc />");
        AppendFunctionSignature(builder, function, "        public ");
        builder.AppendLine(" =>");
        builder.Append("            _provider.InvokeAsync");
        if (!IsVoid(function.ReturnType))
        {
            builder.Append('<').Append(TypeName(function.ReturnType)).Append('>');
        }

        builder.AppendLine("(");
        builder.AppendLine("                ModuleDefinition.Value,");
        builder
            .Append("                new global::DotPython.PythonFunctionInvocation(")
            .Append(Literal(function.PythonName));
        if (function.Parameters.Count != 0)
        {
            builder.AppendLine(",");
            builder.Append("                    [");
            for (var index = 0; index < function.Parameters.Count; index++)
            {
                if (index != 0)
                {
                    builder.Append(", ");
                }

                builder.Append(function.Parameters[index].ClrName);
            }

            builder.Append(']');
        }

        builder.AppendLine("),");
        builder.AppendLine("                cancellationToken");
        builder.AppendLine("            );");
    }

    private static void AppendContractFactory(StringBuilder builder, PythonModuleContract contract)
    {
        builder.AppendLine(
            "    private static global::DotPython.Contracts.PythonModuleContract CreateContract() =>"
        );
        builder.AppendLine("        new(");
        builder
            .Append("            ")
            .Append(contract.FormatVersion.ToString(CultureInfo.InvariantCulture))
            .AppendLine(",");
        builder.Append("            ").Append(Literal(contract.ModuleName)).AppendLine(",");
        builder.Append("            ").Append(Literal(contract.ClrNamespace)).AppendLine(",");
        builder.Append("            ").Append(Literal(contract.ClrTypeName)).AppendLine(",");
        builder
            .Append("            global::DotPython.Contracts.PythonModuleStatePolicy.")
            .Append(contract.StatePolicy)
            .AppendLine(",");
        builder.AppendLine("            [");
        for (var index = 0; index < contract.Functions.Count; index++)
        {
            AppendFunctionContract(builder, contract.Functions[index], "                ");
            builder.AppendLine(index + 1 == contract.Functions.Count ? string.Empty : ",");
        }

        builder.AppendLine("            ]");
        builder.AppendLine("        );");
    }

    private static void AppendFunctionContract(
        StringBuilder builder,
        PythonFunctionContract function,
        string indent
    )
    {
        builder
            .Append(indent)
            .AppendLine("new global::DotPython.Contracts.PythonFunctionContract(");
        builder.Append(indent).Append("    ").Append(Literal(function.PythonName)).AppendLine(",");
        builder.Append(indent).Append("    ").Append(Literal(function.ClrName)).AppendLine(",");
        builder
            .Append(indent)
            .Append("    global::DotPython.Contracts.PythonCallShape.")
            .Append(function.CallShape)
            .AppendLine(",");
        builder.Append(indent).AppendLine("    [");
        for (var index = 0; index < function.Parameters.Count; index++)
        {
            AppendParameterContract(builder, function.Parameters[index], indent + "        ");
            builder.AppendLine(index + 1 == function.Parameters.Count ? string.Empty : ",");
        }

        builder.Append(indent).AppendLine("    ],");
        AppendTypeContract(builder, function.ReturnType, indent + "    ");
        builder.AppendLine();
        builder.Append(indent).Append(')');
    }

    private static void AppendParameterContract(
        StringBuilder builder,
        PythonParameterContract parameter,
        string indent
    )
    {
        builder
            .Append(indent)
            .AppendLine("new global::DotPython.Contracts.PythonParameterContract(");
        builder.Append(indent).Append("    ").Append(Literal(parameter.PythonName)).AppendLine(",");
        builder.Append(indent).Append("    ").Append(Literal(parameter.ClrName)).AppendLine(",");
        builder
            .Append(indent)
            .Append("    global::DotPython.Contracts.PythonParameterKind.")
            .Append(parameter.Kind)
            .AppendLine(",");
        builder
            .Append(indent)
            .Append("    ")
            .Append(parameter.HasDefault ? "true" : "false")
            .AppendLine(",");
        AppendTypeContract(builder, parameter.Type, indent + "    ");
        builder.AppendLine();
        builder.Append(indent).Append(')');
    }

    private static void AppendTypeContract(
        StringBuilder builder,
        PythonTypeContract type,
        string indent
    )
    {
        builder.Append(indent).AppendLine("new global::DotPython.Contracts.PythonTypeContract(");
        builder.Append(indent).Append("    ").Append(Literal(type.PythonName)).AppendLine(",");
        builder.Append(indent).Append("    ").Append(Literal(type.ClrTypeName)).AppendLine(",");
        builder
            .Append(indent)
            .Append("    ")
            .Append(type.IsNullable ? "true" : "false")
            .AppendLine(",");
        builder
            .Append(indent)
            .Append("    ")
            .Append(type.IsValueType ? "true" : "false")
            .AppendLine(",");
        builder.Append(indent).Append("    ").Append(type.IsClsCompliant ? "true" : "false");
        if (type.TypeArguments.Count != 0)
        {
            builder.AppendLine(",");
            builder.Append(indent).AppendLine("    [");
            for (var index = 0; index < type.TypeArguments.Count; index++)
            {
                AppendTypeContract(builder, type.TypeArguments[index], indent + "        ");
                builder.AppendLine(index + 1 == type.TypeArguments.Count ? string.Empty : ",");
            }

            builder.Append(indent).AppendLine("    ]");
            builder.Append(indent).Append(')');
            return;
        }

        builder.AppendLine();
        builder.Append(indent).Append(')');
    }

    private static string TypeName(PythonTypeContract type)
    {
        var name = "global::" + type.ClrTypeName;
        if (type.TypeArguments.Count != 0)
        {
            name += "<" + string.Join(", ", type.TypeArguments.Select(TypeName)) + ">";
        }

        if (!type.IsNullable)
        {
            return name;
        }

        return type.IsValueType ? $"global::System.Nullable<{name}>" : name + "?";
    }

    private static bool IsVoid(PythonTypeContract type) =>
        string.Equals(type.ClrTypeName, "System.Void", StringComparison.Ordinal);

    private static string Literal(string value)
    {
        var builder = new StringBuilder(value.Length + 2).Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                case < ' ':
                    builder
                        .Append("\\u")
                        .Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }

        return builder.Append('"').ToString();
    }
}
