using System.Security.Cryptography;
using System.Text;

namespace DotPython.ParserGenerator.Generation;

public static class PythonParserSourceGenerator
{
    public static string Generate(string grammarSource)
    {
        ArgumentNullException.ThrowIfNull(grammarSource);

        var grammar = PegGrammar.Parse(grammarSource);
        var normalizedSource = grammarSource.ReplaceLineEndings("\n");
        if (!normalizedSource.EndsWith('\n'))
        {
            normalizedSource += '\n';
        }

        var fingerprint = Convert.ToHexStringLower(
            SHA256.HashData(Encoding.UTF8.GetBytes(normalizedSource))
        );
        var normalizedRules = PegGrammar.NormalizeRuleSource(grammarSource);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated from Grammar/python314-subset.gram. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("namespace DotPython.ParserGenerator.Generation;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedPythonGrammar");
        builder.AppendLine("{");
        builder.Append("    internal const string SourceSha256 = \"");
        builder.Append(fingerprint);
        builder.AppendLine("\";");
        builder.Append("    internal const int RuleCount = ");
        builder.Append(grammar.RuleCount);
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("    private const string GrammarSource = \"\"\"");
        foreach (var line in normalizedRules.Split('\n'))
        {
            builder.Append("        ");
            builder.AppendLine(line);
        }

        builder.AppendLine("        \"\"\";");
        builder.AppendLine();
        builder.AppendLine(
            "    internal static PegGrammar Grammar { get; } = PegGrammar.Parse(GrammarSource);"
        );
        builder.AppendLine("}");
        return builder.ToString().ReplaceLineEndings("\n");
    }
}
